name: Lint app

on: pull_request

jobs:
  Lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Python 3.11
        uses: actions/setup-python@v2
        with::
          python-version:'3.11'
          architecture:'x64'
          
      - name: Poetry
        uses: snok/install-poetry@v2
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        working-directory: ./project
        run: poetry install --no-root
        
      - name: Run black
       working-directory: ./project
       run: poetry run black .
      
      - name: Run flake8
       working-directory: ./project
       run: poetry run flake .
      
